---
title: 阅合社实体类图
---
classDiagram
    direction LR
    class User {
        <<用户>>
        +string Nickname 昵称
        +string Account 账号
        +string Password 密码
        +Guid? Avatar 头像
        +string? WeChatID 微信号
        +Role Role 角色
        +int ReadingBeans 阅豆
        +string InvitationCode 邀请码
        +Status Status 状态
    }

    class Invite{
        <<邀请>>
        +Guid InviterID 邀请人ID
        +Guid BeInviterID 被邀请人ID
        +int RebateReadingBeans 返利阅豆
    }

    class Assignment {
        <<任务>>
        +Guid PublisherID 发布人ID
        +string Title 标题
        +Guid RequirementID 需求ID
        +Guid TypeID 类型ID
        +int Index 位序
        +PinType PinType 置顶类型
        +string? Link 链接
        +Guid? QRCodeFileID 二维码文件ID
        +string? Data 数据
        +int CompletedCount 完成数量
        +Status Status 状态
        +int EditCount 剩余编辑次数
        +bool Enabled 启用标识
    }

    class AssignmentTypeGroup {
        <<任务类型组>>
        +string Name 名称
        +int Index 位序
    }
    
    class AssignmentType {
        <<任务类型>>
        +string Name 名称
        +Guid? ParentID 父级类型ID
        +Guid? TutorialDocumentID 教程文档ID
        +string? TypeData 类型数据
        +string PublishDescription 发布描述
        +Guid GroupID 类型组ID
        +Guid IconFileID 图标文件ID
        +int EditCount 剩余编辑次数
        +int Index 位序
    }

    class AssignmentRequirement {
        <<任务需求>>
        +string Name 名称
        +string Description 描述
        +int RewardPerCompletion 单次完成奖励
        +int PublishPrice 发布价格
        +string ReadingBeansDescription 阅豆说明
        +Guid AssignmentType 任务类型ID
        +int Index 位序
    }

    class Order {
        <<订单>>
        +Guid UserID 用户ID
        +string OrderNumber 订单号
        +decimal Amount 金额
        +Guid CommodityID 商品ID
        +OrderStatus Status 状态
    }

    class Commodity {
        <<商品>>
        +decimal Price 价格
        +int ReadingBeansAmount 阅豆数量
        +int Index 位序
        +bool Enabled 启用标识
    }

    class CompletionRecord {
        <<完成任务记录>>
        +Guid AssignmentID 任务ID
        +Guid ScreenshotID 完成要求截图ID
        +Guid OperatorID 操作人ID
        +Status Status 状态
    }

    class AssignmentAuditRecord {
        <<任务审核记录>>
        +Guid AssignmentID 任务ID
        +Guid ReporterID 举报人ID
        +string ReportDescription 举报说明
        +Guid? ReportAttachmentID 举报附件ID
        +Guid? AuditorID 审核人ID
        +string? AuditDescription 审核说明
        +DateTime? AuditTime 审核时间
        +Status Status 状态
    }

    class CompletionAuditRecord {
        <<完成任务审核记录>>
        +Guid CompletionRecordID 完成任务记录ID
        +Guid ReporterID 举报人ID
        +string ReportDescription 举报说明
        +Guid? ReportAttachmentID 举报附件ID
        +Guid? AuditorID 审核人ID
        +string? AuditDescription 审核说明
        +DateTime? AuditTime 审核时间
        +Status Status 状态
    }

    class UserAuditRecord {
        <<用户审核记录>>
        +Guid UserID 用户ID
        +Guid ReporterID 举报人ID
        +string ReportDescription 举报说明
        +Guid? ReportAttachmentID 举报附件ID
        +Guid? AuditorID 审核人ID
        +string? AuditDescription 审核说明
        +DateTime? AuditTime 审核时间
        +Status Status 状态
    }

    class UserCheckInRecord {
        <<用户打卡记录>>
        +Guid UserID 用户ID
        +DateTime CheckInDate 打卡日期
    }

    class ReadingBeansDetail {
        <<阅豆明细>>
        +Guid UserID 用户ID
        +int BeforeAmount 变更前数量
        +int ChangeAmount 变更数量
        +int AfterAmount 变更后数量
        +ReadingBeansSource Source 来源
        +string? SourceData 来源数据
        +string Description 说明
    }

    class OperationDocument {
        <<运营文档>>
        +string Name 名称
        +int Index 位序
        +string Content 内容
        +Guid TypeID 类型ID
        +string Code 代码
    }

    class OperationDocumentType {
        <<运营文档类型>>
        +string Name 名称
        +Guid? ParentID 父级类型ID
        +int Index 位序
    }

    class StoredFile {
        <<已存储的文件>>
        +string FileName 文件名
        +string Extension 后缀名
        +long Size 文件大小
        +string StoragePath 存储路径
        +string? ContentType 内容类型
        +Guid? UploaderID 上传者ID
    }

    %% 关系定义
    User "1" --> "1" StoredFile : 头像存储
    User "1" --> "*" Invite : 邀请注册
    Invite "1" --> "1" ReadingBeansDetail : 充值返利
    User "1" --> "*" ReadingBeansDetail : 阅豆明细
    User "1" --> "*" Order : 充值
    Order "1" --> "1" ReadingBeansDetail : 充值入账
    Order "*" --> "1" Commodity : 充值商品
    User "1" <--> "*" UserAuditRecord : 举报/被举报/审核
    UserAuditRecord "1" --> "1" StoredFile : 举报附件存储
    User "1" <--> "*" AssignmentAuditRecord : 举报/审核
    AssignmentAuditRecord "1" --> "1" StoredFile : 举报附件存储
    User "1" <--> "*" CompletionAuditRecord : 举报/审核
    CompletionAuditRecord "1" --> "1" StoredFile : 举报附件存储
    User "1" --> "*" UserCheckInRecord : 打卡
    UserCheckInRecord "1" --> "1" ReadingBeansDetail : 打卡奖励
    User "1" --> "*" Assignment : 发布任务
    User "1" --> "*" CompletionRecord : 完成任务
    CompletionRecord "1" --> "*" CompletionAuditRecord : 被举报
    Assignment "1" --> "*" AssignmentAuditRecord : 被举报
    Assignment "1" --> "*" CompletionRecord : 被完成
    CompletionRecord "1" --> "1" StoredFile : 完成要求截图存储
    AssignmentType "*" --> "1" Assignment : 每个类型有多个任务
    AssignmentType "*" --> "1" AssignmentRequirement : 每个类型有多个需求
    AssignmentType "1" --> "*" OperationDocument : 每个类型有一个教程文档
    AssignmentType "1" --> "1" StoredFile : 图标文件存储
    AssignmentRequirement "*" --> "1" Assignment : 每个需求有多个任务
    AssignmentTypeGroup "1" --> "*" AssignmentType : 每个组有多个类型
    OperationDocument "*" --> "1" OperationDocumentType : 每个类型有多个运营文档