/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface RunCliOptions {
  input: string
  command: string
  plugin?: Array<string>
  options: Array<string>
}
export declare function runCli(options: RunCliOptions): void
