/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface RunCliOptions {
  input: string
  command: string
  plugin?: Array<string>
  options: Array<string>
}
export interface GetHelpTreeOptions {
  plugin?: Array<string>
}
export interface HelpOptionDescriptor {
  long: string
  short?: string
  valueName?: string
  required: boolean
  multiple: boolean
  defaultValue?: string
  description: string
}
export interface HelpCommandDescriptor {
  name: string
  summary: string
  description?: string
  aliases: Array<string>
  options: Array<HelpOptionDescriptor>
  examples: Array<string>
  pluginName?: string
  pluginVersion?: string
}
export declare function runCli(options: RunCliOptions): void
export declare function getHelpTree(options?: GetHelpTreeOptions | null): Array<HelpCommandDescriptor>
