/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 生成工具箱配置项 */
export interface FrontendTkGenOps {
  /** swagger json 入口路径 */
  input: string
  /** 服务输出路径 */
  serviceOutput?: Array<string>
  /** 模型输出路径 */
  modelOutput?: string
  /** service 模式 */
  serviceMode?: string
  /** 是否生成基础文件 */
  genBaseService?: boolean
}
export declare function frontendTkGen(options: FrontendTkGenOps): void
